### ISSUE TITLE
Alpha is multiplied with RGB

### ISSUE THREAD

**Issue by SebastianNette** [lukeapage/pngjs2#23]
Hi Guys,

I don't know what I'm doing wrong, but it seems that the alpha is always multiplied with the rgb values. Do I need to set any specific values? I can't find a tutorial for using pngjs2. (I mean when saving the file)

**Comment by lukeapage** [comment]
the output should be an array of numbers, size equaling width * height * 4. Each pixel is 4 bytes, R,G,B,A

pngsjs2 shouldn't be multiplying any alpha values, but it may depend on the png being parsed - is it all transparent png's you are having a problem with or just one? the readme is our documentation.

**Comment by SebastianNette** [comment]
Hi lukeapage,

thanks for your quick reply.

Reading the files works absolutely fine for me, the RGBA values are all correct.

In:
```javascript
var image = new PNG({ filterType: -1, width: 1024, height: 1024 });
fs.createReadStream(file).pipe(new PNG({ filterType: -1 })).on('parsed', function() {
  this.bitblt(image, 0, 0, Math.min(image.width, this.width), Math.min(image.height, this.height), 0, 0);
});
```

image.data contains all the correct rgba values,

Now I manipulate the data,

```javascript
function setPixel(x, y, r, g) {
  var i = (y * image.width + x) << 2;
  image.data[i] = r; // r channel
  image.data[i+1] = g; // g channel
  image.data[i+3] = 10; // a channel
}
```

Out:
```javascript
image.pack().pipe(fs.createWriteStream(file)).on('finish', function() {
  //...
});
```

I also tried with filterType: 0 but no difference.

To make it simpler:

```javascript
var fs = require('fs');
var PNG = require('pngjs2').PNG;

var image = new PNG({ filterType: -1, width: 10, height: 10 });
for(var idx = 0; idx < image.width * image.height * 4; idx += 4) {
  image.data[idx] = 1;
  image.data[idx+1] = 2;
  image.data[idx+2] = 3;
  image.data[idx+3] = 4;
}

image.pack().pipe(fs.createWriteStream('test.png')).on('finish', function() {
  console.log("file saved");
});
```

Results in [0,0,0,4,0,0,0,4,0,0,0,4,...]

Doesn't matter which filterType I choose. Any Idea why this happens?

**Comment by lukeapage** [comment]
hrmm strange,  I will have to debug.

**Comment by SebastianNette** [comment]
I think the issue is not in your lib but instead canvas is premultiplying the alpha. Which I didn't expect. I think this can be closed now.

**Comment by lukeapage** [comment]
great news,  thanks for letting me know.
